### ISSUE TITLE
Converting yaml file from cricstats fails

### ISSUE THREAD

**Issue by rahulkanchi** [tvganesh/yorkpy#1]
yka.convertYaml2PandasDataframeT20("1184258.yaml","./","./data")
/space/pyds/venv/lib/python3.5/site-packages/yorkpy/analytics.py:76: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  a=yaml.load(f)
Converting file: 1184258.yaml
/space/pyds/venv/lib/python3.5/site-packages/yorkpy/analytics.py:87: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.
To accept the future behavior, pass 'sort=False'.
To retain the current behavior and silence the warning, pass 'sort=True'.
  team1=pd.concat([team1,b])
Team1:diff: ['byes', 'penalty', 'noballs']
team1: byes
team1: penalty
team1: noballs
/space/pyds/venv/lib/python3.5/site-packages/yorkpy/analytics.py:145: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.
To accept the future behavior, pass 'sort=False'.
To retain the current behavior and silence the warning, pass 'sort=True'.
  team2=pd.concat([team2,b])
Team2:Extras not present
Team1-missing columns: []
Team2-missing columns: ['noballs', 'wides', 'extras_dict', 'fielders', 'penalty', 'legbyes', 'byes']
Adding:team2: noballs
Adding:team2: wides
Adding:team2: extras_dict
Adding:team2: fielders
Adding:team2: penalty
Adding:team2: legbyes
Adding:team2: byes
Length of info field= 12
Wintype= wickets
Win value= wickets
win margin= 9
Here11
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/space/pyds/venv/lib/python3.5/site-packages/yorkpy/analytics.py", line 313, in convertYaml2PandasDataframeT20
    outfile=a['info']['teams'][0]+ '-' + a['info']['teams'][1] + '-' +a['info']['dates'][0].strftime('%Y-%m-%d') + '.csv'
AttributeError: 'str' object has no attribute 'strftime'

========================================

The file, 1184258.yaml, is under all.zip downloaded from cricstat.

**Comment by tvganesh** [comment]
Is the yaml file from Cricsheet?

**Comment by rahulkanchi** [comment]
Yes, its from cricsheet. The file, 1184258.yaml, is under all.zip downloaded from cricsheet

**Comment by rahulkanchi** [comment]
Hi Ganesh,

Had a chance to look into this issue? I am unable to upload that yaml file as github doesn't support attaching yaml file. So uploaded all.zip file. Please let me know if you need any further information.

[all.zip](https://github.com/tvganesh/yorkpy/files/3587717/all.zip)

Thanks in advance

**Comment by rahulkanchi** [comment]
Please ignore, I accidentally closed the issue.

**Comment by tvganesh** [comment]
No, did not have a chance to look at it. Will do when I get time

Regards
Ganesh

<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=2d8bc5ed-5e45-4a99-ac81-d936f2c3fd1a>
I’m
protected online with Avast Free Antivirus. Get it here — it’s free forever.
<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=2d8bc5ed-5e45-4a99-ac81-d936f2c3fd1a>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by skwolvie** [comment]
**Converting yaml files to pandas df fails**

yka.convertAllYaml2PandasDataframesT20("YamlDtsets//INTLT20_YAML_Dtsets", "..//..//IntlT20//IntlT20-Matches")

[convertAllYaml2PandasDataframesT20]
- Fails to convert all YAML files in the source directory and save csv in the destination directory

[logs/screenshots]

File no= 0
Converting file: 1001349.yaml
C:\Users\sachi\Anaconda3\lib\site-packages\yorkpy\analytics.py:76: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  a=yaml.load(f)
C:\Users\sachi\Anaconda3\lib\site-packages\yorkpy\analytics.py:87: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  team1=pd.concat([team1,b])
Team1:diff: ['penalty']
team1: penalty
C:\Users\sachi\Anaconda3\lib\site-packages\yorkpy\analytics.py:145: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  team2=pd.concat([team2,b])
Team2:diff: ['penalty', 'noballs']
team2: penalty
team2: noballs
Team1-missing columns: []
Team2-missing columns: []
Length of info field= 10
Wintype= wickets
Win value= wickets
win margin= 5
..//..//IntlT20//IntlT20-Matches\Australia-Sri Lanka-2017-02-17.csv
Dataframe shape= (250, 38)


File no= 1
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-7-06b6a4d7924e> in <module>
----> 1 yka.convertAllYaml2PandasDataframesT20("YamlDtsets//INTLT20_YAML_Dtsets", "..//..//IntlT20//IntlT20-Matches")

~\Anaconda3\lib\site-packages\yorkpy\analytics.py in convertAllYaml2PandasDataframesT20(source, dest)
    379          print("\n\nFile no=",index)
    380          if file.endswith(".yaml"):
--> 381              df, filename = convertYaml2PandasDataframeT20(file, source, dest)
    382              #print(filename)
    383 

~\Anaconda3\lib\site-packages\yorkpy\analytics.py in convertYaml2PandasDataframeT20(infile, source, dest)
     68     '''
     69 
---> 70     os.chdir(source)
     71     os.path.join(source,infile)
     72 

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'YamlDtsets//INTLT20_YAML_Dtsets'

![image](https://user-images.githubusercontent.com/22741452/77995597-bbdf4580-7349-11ea-8eaf-cd97e061e366.png)
![image](https://user-images.githubusercontent.com/22741452/77995612-c4d01700-7349-11ea-8bf6-30682fea9672.png)

**Comment by tvganesh** [comment]
yka.convertAllYaml2PandasDataframesT20("./cricket-package/yorkpyPkg/nifi/ipl",",/backup/software/nifi/ipldata")

yka.convertAllYam2PandasDataframes(source,target)

**Comment by tvganesh** [comment]
Hi,
   Please see my post https://gigadom.in/2020/02/29/ranking-t20-players-in-intl-t20-ipl-bbl-and-natwest-using-yorkpy/. I did the conversion for all T20 formats about 3-4 weeks back. There is some issue with the folders. You can check the code in Github
